# require "vladify/delayed_job"
require "vladify/delayed_job_monit"
require "vladify/fast_gettext"
# require "vladify/gettext"
# require "vladify/thinking_sphinx"
# require "vladify/ultrasphinx"
# require "vladify/whenever"
# require "vladify/workling"

set :application, "benyehuda.org"
set :repository, "git@alpha.astrails.com:benyehuda/cases_server"
set :domain, "astrails@benyehuda.astrails.com"
